// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/abci_info": {
            "get": {
                "description": "Get info about the application. Upon success, the Cache-Control header will be set with the default maximum age.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Get info about the application",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcAbciInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/block": {
            "get": {
                "description": "Get Block. If the height field is set to a non-default value, upon success, the Cache-Control header will be set with the default maximum age.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Get block at a specified height",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 14992000,
                        "description": "height to return. If no height is provided, it will fetch validator set which corresponds to the latest block.",
                        "name": "height",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcBlock"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/consensus_params": {
            "get": {
                "description": "Get consensus parameters. If the height field is set to a non-default value, upon success, the Cache-Control header will be set with the default maximum age.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Get consensus parameters",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 14992000,
                        "description": "height to return. If no height is provided, it will fetch validator set which corresponds to the latest block.",
                        "name": "height",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcConsensusParams"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/consensus_state": {
            "get": {
                "description": "Get consensus state. Not safe to call from inside the ABCI application during a block execution.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Get consensus state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcConsensusState"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/dump_consensus_state": {
            "get": {
                "description": "Get consensus state. Not safe to call from inside the ABCI application during a block execution.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Get consensus state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcDumpConsensusState"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get node health. Returns empty result (200 OK) on success, no response - in case of an error.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Node heartbeat",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcHealth"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/net_info": {
            "get": {
                "description": "Get network info",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Network informations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcNetInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/node_info": {
            "get": {
                "description": "Information about the connected node",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LCD"
                ],
                "summary": "The properties of the connected node",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LcdNodeInfo"
                        }
                    },
                    "500": {
                        "description": "Failed to query node status"
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Get Tendermint status including node info, pubkey, latest block hash, app hash, block height and time.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Node Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcStatus"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/tx": {
            "get": {
                "description": "Get Transaction",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Node heartbeat",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0xAAAE86DA167A62EF57F30B857E9F37FE4E13060FE2569BB700FB286D03F1F454",
                        "description": "Transaction hash (0x + Hash)",
                        "name": "hash",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcTx"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        },
        "/validators": {
            "get": {
                "description": "Get Validators. Validators are sorted by voting power. If the height field is set to a non-default value, upon success, the Cache-Control header will be set with the default maximum age.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC"
                ],
                "summary": "Get validator set at a specified height",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 14992000,
                        "description": "height to return. If no height is provided, it will fetch validator set which corresponds to the latest block.",
                        "name": "height",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Number of entries per page (max: 100)",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RpcValidators"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.RpcError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.LcdNodeInfo": {
            "type": "object",
            "properties": {
                "application_version": {
                    "type": "object",
                    "properties": {
                        "build_deps": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "build_tags": {
                            "type": "string"
                        },
                        "commit": {
                            "type": "string"
                        },
                        "cosmos_sdk_version": {
                            "type": "string"
                        },
                        "go": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "server_name": {
                            "type": "string"
                        },
                        "version": {
                            "type": "string"
                        }
                    }
                },
                "node_info": {
                    "type": "object",
                    "properties": {
                        "channels": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "listen_addr": {
                            "type": "string"
                        },
                        "moniker": {
                            "type": "string"
                        },
                        "network": {
                            "type": "string"
                        },
                        "other": {
                            "type": "object",
                            "properties": {
                                "rpc_address": {
                                    "type": "string"
                                },
                                "tx_index": {
                                    "type": "string"
                                }
                            }
                        },
                        "protocol_version": {
                            "type": "object",
                            "properties": {
                                "app": {
                                    "type": "string"
                                },
                                "block": {
                                    "type": "string"
                                },
                                "p2p": {
                                    "type": "string"
                                }
                            }
                        },
                        "version": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "model.RpcAbciInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "response": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "string"
                                },
                                "last_block_app_hash": {
                                    "type": "string"
                                },
                                "last_block_height": {
                                    "type": "string"
                                },
                                "version": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "model.RpcBlock": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "block": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "txs": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "evidence": {
                                    "type": "object",
                                    "properties": {
                                        "evidence": {
                                            "type": "array",
                                            "items": {}
                                        }
                                    }
                                },
                                "header": {
                                    "type": "object",
                                    "properties": {
                                        "app_hash": {
                                            "type": "string"
                                        },
                                        "chain_id": {
                                            "type": "string"
                                        },
                                        "consensus_hash": {
                                            "type": "string"
                                        },
                                        "data_hash": {
                                            "type": "string"
                                        },
                                        "evidence_hash": {
                                            "type": "string"
                                        },
                                        "height": {
                                            "type": "string"
                                        },
                                        "last_block_id": {
                                            "type": "object",
                                            "properties": {
                                                "hash": {
                                                    "type": "string"
                                                },
                                                "parts": {
                                                    "type": "object",
                                                    "properties": {
                                                        "hash": {
                                                            "type": "string"
                                                        },
                                                        "total": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "last_commit_hash": {
                                            "type": "string"
                                        },
                                        "last_results_hash": {
                                            "type": "string"
                                        },
                                        "next_validators_hash": {
                                            "type": "string"
                                        },
                                        "proposer_address": {
                                            "type": "string"
                                        },
                                        "time": {
                                            "type": "string"
                                        },
                                        "validators_hash": {
                                            "type": "string"
                                        },
                                        "version": {
                                            "type": "object",
                                            "properties": {
                                                "block": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "last_commit": {
                                    "type": "object",
                                    "properties": {
                                        "block_id": {
                                            "type": "object",
                                            "properties": {
                                                "hash": {
                                                    "type": "string"
                                                },
                                                "parts": {
                                                    "type": "object",
                                                    "properties": {
                                                        "hash": {
                                                            "type": "string"
                                                        },
                                                        "total": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "height": {
                                            "type": "string"
                                        },
                                        "round": {
                                            "type": "integer"
                                        },
                                        "signatures": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "block_id_flag": {
                                                        "type": "integer"
                                                    },
                                                    "signature": {
                                                        "type": "string"
                                                    },
                                                    "timestamp": {
                                                        "type": "string"
                                                    },
                                                    "validator_address": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "block_id": {
                            "type": "object",
                            "properties": {
                                "hash": {
                                    "type": "string"
                                },
                                "parts": {
                                    "type": "object",
                                    "properties": {
                                        "hash": {
                                            "type": "string"
                                        },
                                        "total": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "model.RpcConsensusParams": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "block": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "txs": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "evidence": {
                                    "type": "object",
                                    "properties": {
                                        "evidence": {
                                            "type": "array",
                                            "items": {}
                                        }
                                    }
                                },
                                "header": {
                                    "type": "object",
                                    "properties": {
                                        "app_hash": {
                                            "type": "string"
                                        },
                                        "chain_id": {
                                            "type": "string"
                                        },
                                        "consensus_hash": {
                                            "type": "string"
                                        },
                                        "data_hash": {
                                            "type": "string"
                                        },
                                        "evidence_hash": {
                                            "type": "string"
                                        },
                                        "height": {
                                            "type": "string"
                                        },
                                        "last_block_id": {
                                            "type": "object",
                                            "properties": {
                                                "hash": {
                                                    "type": "string"
                                                },
                                                "parts": {
                                                    "type": "object",
                                                    "properties": {
                                                        "hash": {
                                                            "type": "string"
                                                        },
                                                        "total": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "last_commit_hash": {
                                            "type": "string"
                                        },
                                        "last_results_hash": {
                                            "type": "string"
                                        },
                                        "next_validators_hash": {
                                            "type": "string"
                                        },
                                        "proposer_address": {
                                            "type": "string"
                                        },
                                        "time": {
                                            "type": "string"
                                        },
                                        "validators_hash": {
                                            "type": "string"
                                        },
                                        "version": {
                                            "type": "object",
                                            "properties": {
                                                "block": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "last_commit": {
                                    "type": "object",
                                    "properties": {
                                        "block_id": {
                                            "type": "object",
                                            "properties": {
                                                "hash": {
                                                    "type": "string"
                                                },
                                                "parts": {
                                                    "type": "object",
                                                    "properties": {
                                                        "hash": {
                                                            "type": "string"
                                                        },
                                                        "total": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "height": {
                                            "type": "string"
                                        },
                                        "round": {
                                            "type": "integer"
                                        },
                                        "signatures": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "block_id_flag": {
                                                        "type": "integer"
                                                    },
                                                    "signature": {
                                                        "type": "string"
                                                    },
                                                    "timestamp": {
                                                        "type": "string"
                                                    },
                                                    "validator_address": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "block_id": {
                            "type": "object",
                            "properties": {
                                "hash": {
                                    "type": "string"
                                },
                                "parts": {
                                    "type": "object",
                                    "properties": {
                                        "hash": {
                                            "type": "string"
                                        },
                                        "total": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "model.RpcConsensusState": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "round_state": {
                            "type": "object",
                            "properties": {
                                "height/round/step": {
                                    "type": "string"
                                },
                                "height_vote_set": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "precommits": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            },
                                            "precommits_bit_array": {
                                                "type": "string"
                                            },
                                            "prevotes": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            },
                                            "prevotes_bit_array": {
                                                "type": "string"
                                            },
                                            "round": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "locked_block_hash": {
                                    "type": "string"
                                },
                                "proposal_block_hash": {
                                    "type": "string"
                                },
                                "proposer": {
                                    "type": "object",
                                    "properties": {
                                        "address": {
                                            "type": "string"
                                        },
                                        "index": {
                                            "type": "integer"
                                        }
                                    }
                                },
                                "start_time": {
                                    "type": "string"
                                },
                                "valid_block_hash": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "model.RpcDumpConsensusState": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "round_state": {
                            "type": "object",
                            "properties": {
                                "height/round/step": {
                                    "type": "string"
                                },
                                "height_vote_set": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "precommits": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            },
                                            "precommits_bit_array": {
                                                "type": "string"
                                            },
                                            "prevotes": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            },
                                            "prevotes_bit_array": {
                                                "type": "string"
                                            },
                                            "round": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "locked_block_hash": {
                                    "type": "string"
                                },
                                "proposal_block_hash": {
                                    "type": "string"
                                },
                                "proposer": {
                                    "type": "object",
                                    "properties": {
                                        "address": {
                                            "type": "string"
                                        },
                                        "index": {
                                            "type": "integer"
                                        }
                                    }
                                },
                                "start_time": {
                                    "type": "string"
                                },
                                "valid_block_hash": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "model.RpcError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                }
            }
        },
        "model.RpcHealth": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object"
                }
            }
        },
        "model.RpcNetInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "listeners": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "listening": {
                            "type": "boolean"
                        },
                        "n_peers": {
                            "type": "string"
                        },
                        "peers": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "connection_status": {
                                        "type": "object",
                                        "properties": {
                                            "Channels": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "properties": {
                                                        "ID": {
                                                            "type": "integer"
                                                        },
                                                        "Priority": {
                                                            "type": "string"
                                                        },
                                                        "RecentlySent": {
                                                            "type": "string"
                                                        },
                                                        "SendQueueCapacity": {
                                                            "type": "string"
                                                        },
                                                        "SendQueueSize": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            },
                                            "Duration": {
                                                "type": "string"
                                            },
                                            "RecvMonitor": {
                                                "type": "object",
                                                "properties": {
                                                    "Active": {
                                                        "type": "boolean"
                                                    },
                                                    "AvgRate": {
                                                        "type": "string"
                                                    },
                                                    "Bytes": {
                                                        "type": "string"
                                                    },
                                                    "BytesRem": {
                                                        "type": "string"
                                                    },
                                                    "CurRate": {
                                                        "type": "string"
                                                    },
                                                    "Duration": {
                                                        "type": "string"
                                                    },
                                                    "Idle": {
                                                        "type": "string"
                                                    },
                                                    "InstRate": {
                                                        "type": "string"
                                                    },
                                                    "PeakRate": {
                                                        "type": "string"
                                                    },
                                                    "Progress": {
                                                        "type": "integer"
                                                    },
                                                    "Samples": {
                                                        "type": "string"
                                                    },
                                                    "Start": {
                                                        "type": "string"
                                                    },
                                                    "TimeRem": {
                                                        "type": "string"
                                                    }
                                                }
                                            },
                                            "SendMonitor": {
                                                "type": "object",
                                                "properties": {
                                                    "Active": {
                                                        "type": "boolean"
                                                    },
                                                    "AvgRate": {
                                                        "type": "string"
                                                    },
                                                    "Bytes": {
                                                        "type": "string"
                                                    },
                                                    "BytesRem": {
                                                        "type": "string"
                                                    },
                                                    "CurRate": {
                                                        "type": "string"
                                                    },
                                                    "Duration": {
                                                        "type": "string"
                                                    },
                                                    "Idle": {
                                                        "type": "string"
                                                    },
                                                    "InstRate": {
                                                        "type": "string"
                                                    },
                                                    "PeakRate": {
                                                        "type": "string"
                                                    },
                                                    "Progress": {
                                                        "type": "integer"
                                                    },
                                                    "Samples": {
                                                        "type": "string"
                                                    },
                                                    "Start": {
                                                        "type": "string"
                                                    },
                                                    "TimeRem": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    "is_outbound": {
                                        "type": "boolean"
                                    },
                                    "node_info": {
                                        "type": "object",
                                        "properties": {
                                            "channels": {
                                                "type": "string"
                                            },
                                            "id": {
                                                "type": "string"
                                            },
                                            "listen_addr": {
                                                "type": "string"
                                            },
                                            "moniker": {
                                                "type": "string"
                                            },
                                            "network": {
                                                "type": "string"
                                            },
                                            "other": {
                                                "type": "object",
                                                "properties": {
                                                    "rpc_address": {
                                                        "type": "string"
                                                    },
                                                    "tx_index": {
                                                        "type": "string"
                                                    }
                                                }
                                            },
                                            "protocol_version": {
                                                "type": "object",
                                                "properties": {
                                                    "app": {
                                                        "type": "string"
                                                    },
                                                    "block": {
                                                        "type": "string"
                                                    },
                                                    "p2p": {
                                                        "type": "string"
                                                    }
                                                }
                                            },
                                            "version": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "remote_ip": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "model.RpcStatus": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "node_info": {
                            "type": "object",
                            "properties": {
                                "channels": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "string"
                                },
                                "listen_addr": {
                                    "type": "string"
                                },
                                "moniker": {
                                    "type": "string"
                                },
                                "network": {
                                    "type": "string"
                                },
                                "other": {
                                    "type": "object",
                                    "properties": {
                                        "rpc_address": {
                                            "type": "string"
                                        },
                                        "tx_index": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "protocol_version": {
                                    "type": "object",
                                    "properties": {
                                        "app": {
                                            "type": "string"
                                        },
                                        "block": {
                                            "type": "string"
                                        },
                                        "p2p": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "version": {
                                    "type": "string"
                                }
                            }
                        },
                        "sync_info": {
                            "type": "object",
                            "properties": {
                                "catching_up": {
                                    "type": "boolean"
                                },
                                "earliest_app_hash": {
                                    "type": "string"
                                },
                                "earliest_block_hash": {
                                    "type": "string"
                                },
                                "earliest_block_height": {
                                    "type": "string"
                                },
                                "earliest_block_time": {
                                    "type": "string"
                                },
                                "latest_app_hash": {
                                    "type": "string"
                                },
                                "latest_block_hash": {
                                    "type": "string"
                                },
                                "latest_block_height": {
                                    "type": "string"
                                },
                                "latest_block_time": {
                                    "type": "string"
                                }
                            }
                        },
                        "validator_info": {
                            "type": "object",
                            "properties": {
                                "address": {
                                    "type": "string"
                                },
                                "pub_key": {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "voting_power": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "model.RpcTx": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "hash": {
                            "type": "string"
                        },
                        "height": {
                            "type": "string"
                        },
                        "index": {
                            "type": "integer"
                        },
                        "tx": {
                            "type": "string"
                        },
                        "tx_result": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "codespace": {
                                    "type": "string"
                                },
                                "data": {
                                    "type": "string"
                                },
                                "events": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "attributes": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "properties": {
                                                        "index": {
                                                            "type": "boolean"
                                                        },
                                                        "key": {
                                                            "type": "string"
                                                        },
                                                        "value": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            },
                                            "type": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "gas_used": {
                                    "type": "string"
                                },
                                "gas_wanted": {
                                    "type": "string"
                                },
                                "info": {
                                    "type": "string"
                                },
                                "log": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "model.RpcValidators": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jsonrpc": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "block_height": {
                            "type": "string"
                        },
                        "count": {
                            "type": "string"
                        },
                        "total": {
                            "type": "string"
                        },
                        "validators": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "address": {
                                        "type": "string"
                                    },
                                    "proposer_priority": {
                                        "type": "string"
                                    },
                                    "pub_key": {
                                        "type": "object",
                                        "properties": {
                                            "type": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "voting_power": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
